repos:
  - repo: local
    hooks:
      - id: check-commit-msg
        name: check-commit-msg
        entry: node ./hooks/check-commit-msg.js
        language: node
        stages: [commit-msg]
        args: [feat, fix, test, docs, refactor, style, chore, perf, build, ci]