repos:
  - repo: local
    hooks:
      - id: check-commit-msg
        name: check commit message (local)
        entry: check-commit-msg
        language: python
        verbose: true
        always_run: true
        args: 
          - --commit-type
          - feat 
          - fix 
          - test 
          - docs 
          - refactor 
          - style
          - chore
          - perf
          - build
          - ci
          - --ticket-prefix
          - TO
          - ECS
          - P20E
          - VRS
          - VR
          - RNUG
          - PAP
        stages: [ commit-msg ]