- id: check-commit-msg
  name: check commit message
  entry: check-commit-msg
  description: Checks commit message for Conventional Commits formatting
  language: python
  always_run: true
  stages: [ commit-msg ]